[package]
name = "example_9_indirect_lr_5_level"
version = "2.0.0"
edition = "2021"
[dependencies]
indoc = "2"
example_9_indirect_lr_5_level_parser = { path = "../example_9_indirect_lr_5_level_parser" }