[package]
name = "c_parser"
version = "0.1.0"
edition = "2024"
# We include the test example files since otherwise the macro doesn't recompile when adding files
# or modifying the test files which is annoying.
include = ["src/**/*", "LICENSE", "README.md"]

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
test-grammar-proc-macro = {path = "../../test-grammar-proc-macro"}
