[package]
name = "parser"
version = "2.1.0"
edition = "2021"

[dependencies]
num = "0.4.1"
num-derive = "0.4.2"
num-traits = "0.2.18"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "ppparser_dsl_benchmark"
harness = false
