[package]
name = "example_10_basic_bench"
version = "2.0.0"
edition = "2021"
[dependencies]
indoc = "2"
example_10_basic_bench_parser = { path = "../example_10_basic_bench_parser" }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
harness = false