[package]
name = "runner"
version = "2.1.0"
edition = "2021"
default-run = "runner"

[dependencies]
parser = { path = "../parser" }
generator = { path = "../generator" }
clap = { version = "4.5.9", features = ["derive"] }
anyhow = "1.0.86"
